trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Build
    displayName: Build stage
    
    jobs:
      - job: Build
        displayName: Build
        
        pool: 
         vmImage: 'windows-latest'
        
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'dotnet restore'
            inputs:
              command: restore
              projects: '**/*.sln'
              
          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              projects: '**/*.sln'
              arguments: '--configuration $(buildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet publish'
            inputs:
              command: publish
              publishWebProjects: true
              projects: '**/Blazor.Client.App.csproj'
              arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
              
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
            inputs:
              ArtifactName: 'drop'
      
      - deployment: Blazor_App_Dev
        displayName: Deploy to Dev
        environment: 'dev'
        dependsOn: [Build]
        pool: 
          vmImage: 'windows-latest'
        
        strategy:
         runOnce:
           deploy:
            steps:
              - task: ArchiveFiles@2
                displayName: 'Archive $(Pipeline.Workspace)/drop/Blazor.Client.App.zip'
                inputs:
                  rootFolderOrFile: '$(Pipeline.Workspace)/drop/Blazor.Client.App.zip'
              - task: AzureRmWebAppDeployment@4
                displayName: 'Azure App Service Deploy: Blazor Client App'
                inputs:
                  azureSubscription: 'Hovergen-MSDN (b6f91b45-350a-4373-acdb-9e85a651de6b)'
                  WebAppName: hvg-blazor-ui
                  packageForLinux: '$(Pipeline.Workspace)/drop/Blazor.Client.App.zip'
                  appType: webApp

  

